### PR TITLE
Add notes to capture

### LINKED ISSUE #108: Add notes to capture
**DESC**: admin will add a note/comment on a picture before he approves it.

**DOD**: The admin will be able to add notes on pending pictures. This function will be on the photo details page, where the admin can add a note on the picture and the note is sent with the data when the admin approves the captures.

**GOAL**: As an admin, I want to be able to add notes to the pending captures
Acceptance criteria: The Details page has the ability to add a note to the pending capture so that when the accept button is pressed, the added note is sent with the data

### PR DESCRIPTION
**Pull request by AlainNshimirimana**
This is the feature adds, deletes, and update a note left by admin

### CODE REVIEW

**Review by taerichard — CHANGES_REQUESTED** [review]
Notes entity needs to be capitalized and not building at all.

**Review by gjesionowski — APPROVED** [review]
Looks good

**Review by taerichard — APPROVED** [review]

**Review by NathanaelRorberg — CHANGES_REQUESTED** [review]
Footer covers the section to add notes on the details page. I can't see what I'm typing and can just barely see the button.

**Comment by AlainNshimirimana** [comment]
Can you send me a screenshot?

**Comment by NathanaelRorberg** [comment]
> Can you send me a screenshot?

Capture

**Comment by AlainNshimirimana** [comment]
ok i see. Are you by any chance viewing that on a smaller screen?

**Comment by NathanaelRorberg** [comment]
No it's actually on a bigger monitor. I just tried viewing it on my laptop screen and it looks good. I'll change my review to approval now.

**Review by NathanaelRorberg — APPROVED** [review]

**Comment by NathanaelRorberg** [comment]
just need to resolve branch conflicts now.

**Comment by AlainNshimirimana** [comment]
that's weird because i have a 27 inch monitor and it looks fine. Also I still need to rework this branch to resolve the conflicts with the  new develop branch.

**Pull request merged**
