### PR TITLE
Closes #89

### LINKED ISSUE #89: Login/Logout Page View
DOD: When the login/logout page looks different from other pages. Login page is its own view that shares style with the other pages, but doesn't have navigation, welcome banner, and other things that a user doesn't need when not logged in yet. Inputs for login/password and login button are styled using bootstrap

User Story: If I'm an admin I want the option to login as an admin. If I don't want to login I want to view the application as a user.

### PR DESCRIPTION
**Pull request by NathanaelRorberg**
Removes unnecessary element from login page such as navigation, footer, and pending notification.

### CODE REVIEW

**Review by floydfix — COMMENTED** [review]
There is an extraneous scroll bar hanging out at the bottom of the page.
Plus, this could use SOME styling, checkout 
https://bootsnipp.com/tags/login

**Comment by NathanaelRorberg** [comment]
The extraneous scroll bar is on every page. I could tackle that but I'll put that in a different issue.

**Comment by floydfix** [comment]
Good call

**Comment by NathanaelRorberg** [comment]
I seemed to have accidentally fixed the scroll bar as well (for this page at least). I'm not really sure what it was but I think it was something from the original bootstrap styling.

**Review by floydfix — APPROVED** [review]

**Review by taerichard — APPROVED** [review]

**Comment by gjesionowski** [comment]
This looks good.

**Review by gjesionowski — APPROVED** [review]

**Review by AlainNshimirimana — APPROVED** [review]

**Comment by NathanaelRorberg** [comment]
use email ZackHuel@hotmail.com and password feuiuuuo for testing.
With the absence of a home controller and a non admin site I set the landing page to the login page.

**Pull request merged**
