### PR TITLE
Entitymodel willie

### PR DESCRIPTION
**Pull request by weberwilliamb**
I think this is pretty close to what we want for the entity model. Please let me know your thoughts or issues.

### CODE REVIEW

**Comment by RoEric** [comment]
I think another feature type for animal-related wildlife such as a bird's nest can be added.

**Comment by sruble** [comment]
> I think another feature type for animal-related wildlife such as a bird's nest can be added.

**Comment by weberwilliamb** [comment]
Eric - I think that we can add in more pertinent data once we talk with the client about specific data to capture at the photo points.

**Comment by Sara-webaplication** [comment]
looks so great, I will update my PhotoDataContext from your codes

**Comment by sruble** [comment]
sorry I accidentally cancelled your commit request...

**Pull request merged**
