### PR TITLE
Entity Relationship Diagram Closes #14

### LINKED ISSUE #14: Update the entity model relationship diagram
DOD: When the new EMR Diagram is complete and approved by the client.

### PR DESCRIPTION
**Pull request by weberwilliamb**
Please review the updated ERD.

### CODE REVIEW

**Comment by sruble** [comment]
The updated ERD look good, Willie.

**Review by sruble — COMMENTED** [review]
The ERD looks good

**Review by MaxIgnatyev — APPROVED** [review]
Fine by me, don't really see anything wrong.

**Comment by Bansenauer-Cascadia** [comment]
I suggest you move the PDF document into a separate folder called "docs" located in the repository root

Also, please include the Navigation properties in your diagram rather than the foreign keys

**Review by sruble — APPROVED** [review]

**Pull request closed without merging**
