### PR TITLE
Requirements~Display~DataTypes added to the Entity Model Closes #43

### LINKED ISSUE #43: Create restrictions for entity properties
DOD: When the properties have the correct restrictions for entry place on them and the team approves the changes.

### PR DESCRIPTION
**Pull request by weberwilliamb**
Please review my changes to the Entity Model. I added requirements, display names, and DataTypes. Please let me know if you think anything should be changed.

### CODE REVIEW

**Review by MaxIgnatyev — APPROVED** [review]
Looks fine to me, the user.cs file with the crazy constrains I assume will work..

**Review by Sara-webaplication — APPROVED** [review]

**Comment by Sara-webaplication** [comment]
look good to me

**Review by Bansenauer-Cascadia — COMMENTED** [review]
Looks like some good data model additions.

**Review by sruble — APPROVED** [review]
I approve, Willie

**Pull request merged**
