### PR TITLE
Closes #70

### LINKED ISSUE #70: Create ControllerAction Login
Desc: Create a controller action in the admin controller that allows login based on account info
DOD: A user can login once they enter credentials that match a database.

### PR DESCRIPTION
**Pull request by NathanaelRorberg**
I've created a login get and post action that should work when the view model is valid. I'll need a login view, view model and a database to test and add functionality for using credentials

### CODE REVIEW

**Review by taerichard — APPROVED** [review]
Nice I see the GET and POST when users are logging in.

**Comment by taerichard** [comment]
I am working on the login view for the controller action so I'll add the view and view model on my branch.

**Review by floydfix — COMMENTED** [review]
Is this really all that we can do for this issue? Is the view/view model/etc not able to be done at the same time?

**Comment by NathanaelRorberg** [comment]
@floydfix There are still things needed to be done to this feature for it to fit the DoD. I just need Richards branch with the view

**Review by gjesionowski — APPROVED** [review]

**Review by AlainNshimirimana — APPROVED** [review]

**Review by taerichard — APPROVED** [review]

**Review by floydfix — CHANGES_REQUESTED** [review]
Doesn't compile. User.password is missing

**Comment by NathanaelRorberg** [comment]
Thanks, fixed now.

**Review by floydfix — CHANGES_REQUESTED** [review]
Need to merge develop into your branch, and after you build and run, make sure it starts the same way as it always has, by showing a webpage. Right now i just get a blank page

**Comment by NathanaelRorberg** [comment]
Thanks, Roger for be so thorough! The latest push should solve the problem. Not sure what was causing the 500 error, but merging develop in seemed to fix the problem.

**Review by floydfix — APPROVED** [review]
Looks good

**Pull request merged**
