### PR TITLE
close #73

### LINKED ISSUE #73: Controller method for searching the new database, returns a message if no results
Desc: Create a controller method that will search the database for photos that match the search filters.

DOD: The controller will be able to provide the results that match the search filter, and return a "no result" message if nothing was found. The search filters are photo point id, from/to date, tags, and approval type (approved, denied, pending).

### PR DESCRIPTION
**Pull request by AlainNshimirimana**
If you search without any filters, the program returns all photos from the photostream.
If you search by photo point ID, the program returns a photo with that specific photo point ID.
if you filter by tag name, approval type, or date, you get no result because the photos that we have in the database don't have any tags or approval type linked to them.
Please take a look and let me know how to proceed to the next step of if should merge and work on it later once we have a proper database and data fields set up.

### CODE REVIEW

**Comment by AlainNshimirimana** [comment]
I redid the pull request for the search function.

**Review by NathanaelRorberg — CHANGES_REQUESTED** [review]
search doesn't actually return anything.

**Comment by AlainNshimirimana** [comment]
Nathanael, I cleaned up the code a bit so it should work now. the approval type search filter is still work in progress but other filters should work fine. Also for fromDate and toDate filters, you have to type in mm/dd/yyyy hr:min am/pm. for example **05/08/2020 11:30 PM** . I will try to find a way to make it so you dont have to include the hours in the date search.

**Review by gjesionowski — COMMENTED** [review]
I do get results with no filters or matched filters. No message on an empty search is the only thing I see missing from issue #73

**Comment by AlainNshimirimana** [comment]
I just made another push. If you search for an id less than 1 or an id greater than amount of captures, you should see a "Results Not Found" message. Same thing if no filters were selected.

**Review by NathanaelRorberg — CHANGES_REQUESTED** [review]
Looks good. if I was picky I'd want everything returned if no filters were selected but that's fine.

**Review by floydfix — APPROVED** [review]

**Review by taerichard — APPROVED** [review]

**Review by gjesionowski — APPROVED** [review]

**Review by NathanaelRorberg — APPROVED** [review]

**Pull request merged**
